# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d39103700d94735ac830f9a1d9f7818ca98574d98a9b69fa74e0d6619b91ed57c34277946b81882f2683c7132366fdf34e385c281d2eac58ee5214ff96dc8ce
  db_user: root
  db_password: root
test:
  secret_key_base: 3ce8b58d52bc3639e1480a5d10fb960ca378d13f7a3affc225d558fb73a3fc586994bc63ea7b3a186b5ac1641048694d85f2c89fe6897967f4e24ff39ba9f48e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
